spring.application.name=ai-service
server.port=8086

gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=gemini-2.5-flash
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.max-concurrent-requests=1
gemini.api.max-wait-for-permit-ms=2000
gemini.api.max-retries=0
gemini.api.initial-backoff-ms=1000
gemini.api.max-backoff-ms=5000

rate-limit.requests-per-minute=10
rate-limit.cooldown-seconds=6

spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:5173

logging.level.com.qlda.ai_service=DEBUG
logging.level.com.qlda.ai_service.controller.ChatController=DEBUG
logging.level.com.qlda.ai_service.service.GeminiService=DEBUG